<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
    <AssettoServerSource Condition="'$(AssettoServerSource)' == ''">$(MSBuildProjectDirectory)\..\.tmp\AssettoServer</AssettoServerSource>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(AssettoServerSource)\AssettoServer.Shared\AssettoServer.Shared.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="$(AssettoServerSource)\AssettoServer\AssettoServer.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
